config/routes.rb
Rails.application.routes.draw do
  resources :subject_heading_types
  resources :classification_types
  resources :classifications
  resources :subject_types
  resources :subjects
end

app/controllers/subject_heading_types_controller.rb
class SubjectHeadingTypesController < ApplicationController
  before_action :set_subject_heading_type, only: [:show, :edit, :update, :destroy]
  before_action :check_policy, only: [:index, :new, :create]

  # GET /subject_heading_types
  # GET /subject_heading_types.json
  def index
    @subject_heading_types = SubjectHeadingType.order(:position)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @subject_heading_types }
    end
  end

  # GET /subject_heading_types/1
  # GET /subject_heading_types/1.json
  def show
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @subject_heading_type }
    end
  end

  # GET /subject_heading_types/new
  # GET /subject_heading_types/new.json
  def new
    @subject_heading_type = SubjectHeadingType.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @subject_heading_type }
    end
  end

  # GET /subject_heading_types/1/edit
  def edit
  end

  # POST /subject_heading_types
  # POST /subject_heading_types.json
  def create
    @subject_heading_type = SubjectHeadingType.new(subject_heading_type_params)

    respond_to do |format|
      if @subject_heading_type.save
        format.html { redirect_to @subject_heading_type, notice:  t('controller.successfully_created', model: t('activerecord.models.subject_heading_type')) }
        format.json { render json: @subject_heading_type, status: :created, location: @subject_heading_type }
      else
        format.html { render action: "new" }
        format.json { render json: @subject_heading_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /subject_heading_types/1
  # PUT /subject_heading_types/1.json
  def update
    if params[:move]
      move_position(@subject_heading_type, params[:move])
      return
    end

    respond_to do |format|
      if @subject_heading_type.update(subject_heading_type_params)
        format.html { redirect_to @subject_heading_type, notice:  t('controller.successfully_updated', model: t('activerecord.models.subject_heading_type')) }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @subject_heading_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /subject_heading_types/1
  # DELETE /subject_heading_types/1.json
  def destroy
    @subject_heading_type.destroy

    respond_to do |format|
      format.html { redirect_to subject_heading_types_url, notice: t('controller.successfully_deleted', model: t('activerecord.models.subject_heading_type')) }
      format.json { head :no_content }
    end
  end

  private
  def set_subject_heading_type
    @subject_heading_type = SubjectHeadingType.find(params[:id])
    authorize @subject_heading_type
  end

  def check_policy
    authorize SubjectHeadingType
  end

  def subject_heading_type_params
    params.require(:subject_heading_type).permit(:name, :display_name, :note)
  end
end

app/views/subject_heading_types/_form.html.erb
<%= form_for(@subject_heading_type) do |f| %>
  <%= f.error_messages %>

  <div class="form-group">
    <%= f.label :name %><br />
    <%= f.text_field :name, required: true, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :display_name %><br />
    <%= f.text_area :display_name, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :note %><br />
    <%= f.text_area :note, class: 'form-control' %>
  </div>
  <div class="actions">
    <%= f.submit class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/subject_heading_types/edit.html.erb
<div class="row">
  <div class="col-md-9">
    <h1 class="title"><%= t('page.editing', model: t('activerecord.models.subject_heading_type')) -%></h1>
    <%= render 'form' %>
  </div>

  <div class="col">
    <div class="card card-body">
      <ul>
        <li><%= link_to t('page.show'), @subject_heading_type -%></li>
        <li><%= link_to t('page.back'), subject_heading_types_path -%></li>
      </ul>
    </div>
  </div>
</div>

app/views/subject_heading_types/index.html.erb
<div class="row">
  <div class="col-md-9">
    <h1 class="title"><%= t('page.listing', model: t('activerecord.models.subject_heading_type')) -%></h1>
    <p id="notice"><%= notice %></p>

    <table class="table table-striped index">
      <tr>
        <th id="position"></th>
        <th><%= t('activerecord.attributes.subject_heading_type.name') -%></th>
        <th>
          <%= t('activerecord.attributes.subject_heading_type.display_name') -%>
          /
          <%= t('activerecord.attributes.subject_heading_type.note') -%>
        </th>
        <th></th>
      </tr>

      <%- @subject_heading_types.each do |subject_heading_type| -%>
        <tr class="line<%= cycle("0", "1") -%>">
          <td>
            <%- if policy(subject_heading_type).update? -%>
              <%= move_position(subject_heading_type) -%>
            <%- end -%>
          </td>
          <td><%= subject_heading_type.name -%></td>
          <td>
            <%= link_to subject_heading_type.display_name, subject_heading_type -%>
            <br />
            <%= subject_heading_type.note %>
          </td>
          <td>
            <%- if policy(subject_heading_type).update? -%>
              <%= link_to t('page.edit'), edit_subject_heading_type_path(subject_heading_type) -%>
            <% end %>
            <%- if policy(subject_heading_type).destroy? -%>
              <%= link_to t('page.destroy'), subject_heading_type_path(subject_heading_type), data: {confirm: t('page.are_you_sure')}, method: :delete -%>
            <%- end -%>
          </td>
        </tr>
      <%- end -%>
    </table>

  </div>

  <div class="col">
    <div class="card card-body">
      <ul>
        <%- if policy(SubjectHeadingType).create? -%>
          <li><%= link_to t('page.new', model: t('activerecord.models.subject_heading_type')), new_subject_heading_type_path -%></li>
        <%- end -%>
      </ul>
    </div>
  </div>
</div>

app/views/subject_heading_types/new.html.erb
<div class="row">
  <div class="col-md-9">
    <h1 class="title"><%= t('page.new', model: t('activerecord.models.subject_heading_type')) -%></h1>
    <%= render 'form' %>
  </div>

  <div class="col">
    <div class="card card-body">
    <ul>
      <li><%= link_to t('page.back'), subject_heading_types_path -%></li>
    </ul>
  </div>
</div>

app/views/subject_heading_types/show.html.erb
<div class="row">
  <div class="col-md-9">
    <h1 class="title"><%= t('page.showing', model: t('activerecord.models.subject_heading_type')) -%></h1>
    <p id="notice"><%= notice %></p>

    <p>
      <strong><%= t('activerecord.attributes.subject_heading_type.name') -%>:</strong>
      <%= @subject_heading_type.name -%>
    </p>

    <p>
      <strong><%= t('activerecord.attributes.subject_heading_type.display_name') -%>:</strong>
      <%= @subject_heading_type.display_name -%>
    </p>

    <p>
      <strong><%= t('activerecord.attributes.subject_heading_type.note') -%>:</strong>
      <%= @subject_heading_type.note -%>
    </p>

  </div>

  <div class="col">
    <div class="card card-body">
      <ul>
        <%- if policy(@subject_heading_type).update? -%>
          <li><%= link_to t('page.edit'), edit_subject_heading_type_path(@subject_heading_type) -%></li>
        <%- end -%>
        <li><%= link_to t('page.back'), :back -%></li>
      </ul>
    </div>
  </div>
</div>