config/routes.rb
Rails.application.routes.draw do
  resources :subject_heading_types
  resources :classification_types
  resources :classifications
  resources :subject_types
  resources :subjects
end

app/models/subject.rb
class Subject < ApplicationRecord
  belongs_to :manifestation, touch: true, optional: true
  belongs_to :subject_type
  belongs_to :subject_heading_type
  belongs_to :required_role, class_name: 'Role', foreign_key: 'required_role_id'

  validates_presence_of :term, :subject_type_id, :subject_heading_type_id

  searchable do
    text :term
    time :created_at
    integer :required_role_id
  end

  strip_attributes only: :term

  paginates_per 10
end

# == Schema Information
#
# Table name: subjects
#
#  id                      :bigint           not null, primary key
#  parent_id               :bigint
#  use_term_id             :integer
#  term                    :string
#  term_transcription      :text
#  subject_type_id         :bigint           not null
#  scope_note              :text
#  note                    :text
#  required_role_id        :bigint           default(1), not null
#  lock_version            :integer          default(0), not null
#  created_at              :datetime
#  updated_at              :datetime
#  url                     :string
#  manifestation_id        :integer
#  subject_heading_type_id :integer
#

app/models/subject_type.rb
class SubjectType < ApplicationRecord
  include MasterModel
  has_many :subjects
  validates :name, format: {with: /\A[0-9A-Za-z][0-9a-z_\-]*[0-9a-z]\Z/}
end

# == Schema Information
#
# Table name: subject_types
#
#  id           :bigint           not null, primary key
#  name         :string           not null
#  display_name :text
#  note         :text
#  position     :integer
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#

app/controllers/subjects_controller.rb
class SubjectsController < ApplicationController
  before_action :set_subject, only: [:show, :edit, :update, :destroy]
  before_action :check_policy, only: [:index, :new, :create]
  before_action :prepare_options, only: [:new, :edit]

  # GET /subjects
  # GET /subjects.json
  def index
    sort = {sort_by: 'created_at', order: 'desc'}
    case params[:sort_by]
    when 'name'
      sort[:sort_by] = 'term'
    end
    sort[:order] = 'asc' if params[:order] == 'asc'

    search = Subject.search
    query = params[:query].to_s.strip
    unless query.blank?
      @query = query.dup
      query = query.gsub('　', ' ')
      search.build do
        fulltext query
      end
    end

    search.build do
      order_by sort[:sort_by], sort[:order]
    end

    role = current_user.try(:role) || Role.default
    search.build do
      with(:required_role_id).less_than_or_equal_to role.id
    end

    page = params[:page] || 1
    search.query.paginate(page.to_i, Subject.default_per_page)
    @subjects = search.execute!.results
    session[:params] = {} unless session[:params]
    session[:params][:subject] = params

    flash[:page_info] = {page: page, query: query}

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @subjects }
      format.rss
      format.atom
    end
  end

  # GET /subjects/1
  # GET /subjects/1.json
  def show
    if params[:term]
      subject = Subject.find_by(term: params[:term])
      redirected_to subject
      return
    end

    search = Sunspot.new_search(Manifestation)
    subject = @subject
    search.build do
      with(:subject_ids).equal_to subject.id if subject
    end
    page = params[:work_page] || 1
    search.query.paginate(page.to_i, Manifestation.default_per_page)

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @subject }
    end
  end

  # GET /subjects/new
  def new
    @subject = Subject.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @subject }
    end
  end

  # GET /subjects/1/edit
  def edit
  end

  # POST /subjects
  # POST /subjects.json
  def create
    @subject = Subject.new(subject_params)

    respond_to do |format|
      if @subject.save
        format.html { redirect_to @subject, notice: t('controller.successfully_created', model: t('activerecord.models.subject')) }
        format.json { render json: @subject, status: :created, location: @subject }
      else
        prepare_options
        format.html { render action: "new" }
        format.json { render json: @subject.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /subjects/1
  # PUT /subjects/1.json
  def update
    respond_to do |format|
      if @subject.update(subject_params)
        format.html { redirect_to @subject, notice: t('controller.successfully_updated', model: t('activerecord.models.subject')) }
        format.json { head :no_content }
      else
        prepare_options
        format.html { render action: "edit" }
        format.json { render json: @subject.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /subjects/1
  # DELETE /subjects/1.json
  def destroy
    @subject.destroy

    respond_to do |format|
      format.html { redirect_to subjects_url, notice: t('controller.successfully_deleted', model: t('activerecord.models.subject')) }
      format.json { head :no_content }
    end
  end

  private
  def set_subject
    @subject = Subject.find(params[:id])
    authorize @subject
  end

  def check_policy
    authorize Subject
  end

  def subject_params
    params.require(:subject).permit(
      :parent_id, :use_term_id, :term, :term_transcription,
      :subject_type_id, :note, :required_role_id, :subject_heading_type_id
    )
  end

  def prepare_options
    @subject_heading_types = SubjectHeadingType.select([:id, :display_name, :position])
    @subject_types = SubjectType.select([:id, :display_name, :position])
  end
end

app/views/subjects/_form.html.erb
<%= form_for(@subject) do |f| -%>
  <%= f.error_messages -%>
  <div class="form-group">
    <%= f.label t('activerecord.models.subject_heading_type') -%>
    <%= f.select(:subject_heading_type_id, @subject_heading_types.collect{|s| [s.display_name, s.id]}, {}, {class: 'form-control col-sm-4'}) -%>
  </div>
  <div class="form-group">
    <%= f.label t('activerecord.models.subject_type') -%>
    <%= f.select(:subject_type_id, @subject_types.collect{|s| [s.display_name, s.id]}, {}, {class: 'form-control col-sm-4'}) -%>
  </div>

  <div class="form-group">
    <%= f.label :term -%><br />
    <%= f.text_field :term, class: 'form-control' -%>
  </div>
  <div class="form-group">
    <%= f.label :term_transcription -%><br />
    <%= f.text_field :term_transcription, class: 'form-control' -%>
  </div>
  <div class="form-group">
    <%= f.label :note -%><br />
    <%= f.text_area :note, class: 'form-control' -%>
  </div>
  <div class="actions">
    <%= f.submit class: 'btn btn-primary' %>
  </div>
<%- end -%>

app/views/subjects/edit.html.erb
<div class="row">
  <div class="col-md-9">
    <h1 class="title"><%= t('page.editing', model: t('activerecord.models.subject')) -%></h1>
    <%= render 'form' %>
  </div>

  <div class="col">
    <div class="card card-body">
      <ul>
        <li><%= link_to t('page.show'), @subject -%></li>
        <li><%= link_to t('page.back'), subjects_path -%></li>
      </ul>
    </div>
  </div>
</div>

app/views/subjects/index.html.erb
<div class="row">
  <div class="col-md-9">
    <h1 class="title"><%= t('page.listing', model: t('activerecord.models.subject')) -%></h1>
    <p id="notice"><%= notice %></p>
      
    <div class="search_form">
      <%= form_for :subjects, url: subjects_path, html: {method: 'get'} do -%>
        <p>
          <%= t('page.search_term') -%>: <%= search_field_tag 'query', h(@query), {id: 'search_form_top', class: 'search_form', placeholder: t('page.search_term')} -%>
          <%= submit_tag t('page.search') -%>
        </p>
      <%- end -%>
    </div>

    <table class="table table-striped index">
      <tr>
        <th><%= t('activerecord.attributes.subject.term') -%></th>
        <th></th>
      </tr>
      <%- @subjects.each do |subject| -%>
        <tr class="line<%= cycle("0", "1") -%>">
          <td><%= link_to subject.term, subject -%></td>
          <td>
            <%- if policy(subject).update? -%>
              <%= link_to t('page.edit'), edit_subject_path(subject) -%>
            <%- end -%>
            <%- if policy(subject).destroy? -%>
              <%= link_to t('page.destroy'), subject, data: {confirm: t('page.are_you_sure')}, method: :delete -%>
            <%- end -%>
          </td>
        </tr>
      <%- end -%>
    </table>

    <%= paginate(@subjects) -%>
  </div>

  <div class="col">
    <div class="card card-body">
      <ul>
        <%- if policy(Subject).create? -%>
          <li><%= link_to t('page.new', model: t('activerecord.models.subject')), new_subject_path -%></li>
        <%- end -%>
      </ul>
    </div>
  </div>
</div>

app/views/subjects/new.html.erb
<div class="row">
  <div class="col-md-9">
    <h1 class="title"><%= t('page.new', model: t('activerecord.models.subject')) -%></h1>
    <%= render 'form' %>
  </div>

  <div class="col">
    <div class="card card-body">
      <ul>
        <li><%= link_to t('page.back'), subjects_path -%></li>
      </ul>
    </div>
  </div>
</div>

app/views/subjects/show.html.erb
<div class="row">
  <div class="col-md-9">
    <h1 class="title"><%= t('page.showing', model: t('activerecord.models.subject')) -%></h1>
    <p id="notice"><%= notice %></p>

    <h2 class="resource_title">
      [S]
      <%= @subject.term -%>
    </h2>

    <p>
      <strong><%= t('activerecord.models.subject_heading_type') -%>:</strong>
      <%= link_to @subject.subject_heading_type.display_name, @subject.subject_heading_type -%>
    </p>

    <p>
      <strong><%= t('activerecord.models.subject_type') -%>:</strong>
      <%= link_to @subject.subject_type.display_name, @subject.subject_type -%>
    </p>

    <p>
      <strong><%= t('activerecord.attributes.subject.term_transcription') -%>:</strong>
      <%= @subject.term_transcription -%>
    </p>

    <p>
      <strong><%= t('activerecord.attributes.subject.note') -%>:</strong>
      <%= @subject.note -%>
    </p>
  </div>

  <div class="col">
    <div class="card card-body">
      <ul>
        <li><%= link_to t('page.back'), :back -%></li>
        <% if policy(@subject).update? %>
          <li><%= link_to t('page.edit'), edit_subject_path(@subject) -%></li>
        <% end %>
        <% if policy(@subject).destroy? %>
          <li><%= link_to t('page.destroy'), subject_path(@subject), data: {confirm: t('page.are_you_sure')}, method: :delete -%></li>
        <% end %>
      </ul>
    </div>
  </div>
</div>