config/routes.rb
Rails.application.routes.draw do
  resources :subject_heading_types
  resources :classification_types
  resources :classifications
  resources :subject_types
  resources :subjects
end

app/models/classification.rb
class Classification < ApplicationRecord
  belongs_to :classification_type
  belongs_to :manifestation, touch: true, optional: true

  validates_presence_of :category
  searchable do
    text :category, :note
    integer :classification_type_id
  end
  strip_attributes only: [:category, :url]

  paginates_per 10
end

# == Schema Information
#
# Table name: classifications
#
#  id                     :bigint           not null, primary key
#  parent_id              :integer
#  category               :string           not null
#  note                   :text
#  classification_type_id :integer          not null
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#  lft                    :integer
#  rgt                    :integer
#  manifestation_id       :integer
#  url                    :string
#  label                  :string
#

app/models/classification_type.rb
class ClassificationType < ApplicationRecord
  include MasterModel
  has_many :classifications
  validates :name, format: { with: /\A[0-9a-z][0-9a-z_\-]*[0-9a-z]\Z/ }
end

# == Schema Information
#
# Table name: classification_types
#
#  id           :bigint           not null, primary key
#  name         :string           not null
#  display_name :text
#  note         :text
#  position     :integer
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#

app/controllers/classifications_controller.rb
class ClassificationsController < ApplicationController
  before_action :set_classification, only: [:show, :edit, :update, :destroy]
  before_action :check_policy, only: [:index, :new, :create]
  before_action :get_subject, :get_classification_type

  # GET /classifications
  # GET /classifications.json
  def index
    search = Sunspot.new_search(Classification)
    query = params[:query].to_s.strip
    unless query.blank?
      @query = query.dup
      search.build do
        fulltext query
      end
    end
    unless params[:mode] == 'add'
      subject = @subject
      classification_type = @classification_type
      search.build do
        with(:subject_ids).equal_to subject.id if subject
        with(:classification_type_id).equal_to classification_type.id if classification_type
      end
    end

    page = params[:page] || 1
    search.query.paginate(page.to_i, Classification.default_per_page)
    @classifications = search.execute!.results

    session[:params] = {} unless session[:params]
    session[:params][:classification] = params

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @classifications }
    end
  end

  # GET /classifications/1
  # GET /classifications/1.json
  def show
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @classification }
    end
  end

  # GET /classifications/new
  # GET /classifications/new.json
  def new
    @classification_types = ClassificationType.all
    @classification = Classification.new
    @classification.classification_type = @classification_type

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @classification }
    end
  end

  # GET /classifications/1/edit
  def edit
    @classification_types = ClassificationType.all
  end

  # POST /classifications
  # POST /classifications.json
  def create
    @classification = Classification.new(classification_params)

    respond_to do |format|
      if @classification.save
        format.html { redirect_to @classification, notice: t('controller.successfully_created', model: t('activerecord.models.classification')) }
        format.json { render json: @classification, status: :created, location: @classification }
      else
        @classification_types = ClassificationType.all
        format.html { render action: "new" }
        format.json { render json: @classification.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /classifications/1
  # PUT /classifications/1.json
  def update
    respond_to do |format|
      if @classification.update(classification_params)
        format.html { redirect_to @classification, notice: t('controller.successfully_updated', model: t('activerecord.models.classification')) }
        format.json { head :no_content }
      else
        @classification_types = ClassificationType.all
        format.html { render action: "edit" }
        format.json { render json: @classification.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /classifications/1
  # DELETE /classifications/1.json
  def destroy
    @classification = Classification.find(params[:id])
    @classification.destroy

    respond_to do |format|
      format.html { redirect_to classifications_url, notice: t('controller.successfully_deleted', model: t('activerecord.models.classification')) }
      format.json { head :no_content }
    end
  end

  private
  def set_classification
    @classification = Classification.find(params[:id])
    authorize @classification
  end

  def check_policy
    authorize Classification
  end

  def classification_params
    params.require(:classification).permit(
      :parent_id, :category, :note, :classification_type_id, :url, :label
    )
  end

  def get_classification_type
    @classification_type = ClassificationType.find(params[:classification_type_id]) rescue nil
  end
end

app/views/classifications/_form.html.erb
<%= form_for(@classification) do |f| -%>
  <%= f.error_messages -%>

  <div class="form-group">
    <%= f.label t('activerecord.models.classification_type') -%><br />
    <%= f.select(:classification_type_id, @classification_types.collect{|c| [c.name, c.id]}, {}, {class: 'form-control col-sm-4'}) -%>
  </div>

  <div class="form-group">
    <%= f.label :category -%><br />
    <%= f.text_field :category, class: 'form-control' -%>
  </div>

  <div class="form-group">
    <%= f.label :label -%><br />
    <%= f.text_field :label, class: 'form-control' -%>
  </div>

  <div class="form-group">
    <%= f.label :url -%><br />
    <%= f.url_field :url, class: 'form-control' -%>
  </div>

  <div class="form-group">
    <%= f.label :note -%><br />
    <%= f.text_area :note, class: 'form-control' -%>
  </div>

  <div class="actions">
    <%= f.submit class: 'btn btn-primary' -%>
  </div>
<%- end -%>

app/views/classifications/edit.html.erb
<div class="row">
  <div class="col-md-9">
    <h1 class="title"><%= t('page.editing', model: t('activerecord.models.classification')) -%></h1>
    <%= render 'form' %>
  </div>

  <div class="col">
    <div class="card card-body">
      <ul>
        <li><%= link_to t('page.show'), @classification -%></li>
        <li><%= link_to t('page.back'), classifications_path -%></li>
      </ul>
    </div>
  </div>
</div>

app/views/classifications/index.html.erb
<div class="row">
  <div class="col-md-9">
    <h1 class="title"><%= t('page.listing', model: t('activerecord.models.classification')) -%></h1>
    <p id="notice"><%= notice %></p>

    <div class="search_form">
      <%= form_for :classifications, url: classifications_path, html: {method: 'get'} do -%>
        <p>
          <%= t('page.search_term') -%>: <%= search_field_tag 'query', h(@query), {id: 'search_form_top', class: 'search_form', placeholder: t('page.search_term')} -%>
          <%= submit_tag t('page.search') -%>
        </p>
      <%- end -%>
    </div>

    <table class="table table-striped index">
      <tr>
        <th><%= t('activerecord.attributes.classification.category') -%></th>
        <th><%= t('activerecord.attributes.classification.label') -%></th>
        <th><%= t('activerecord.models.classification_type') -%></th>
        <th></th>
      </tr>

    <%- @classifications.each do |classification| -%>
      <tr class="line<%= cycle("0", "1") -%>">
        <td><%= link_to classification.category, classification -%></td>
        <td><%= classification.label -%></td>
        <td><%= link_to classification.classification_type.display_name, classification.classification_type -%></td>
        <td>
          <%- if policy(classification).destroy? -%>
            <%= link_to t('page.edit'), edit_classification_path(classification) -%>
            <%= link_to t('page.destroy'), classification, data: {confirm: t('page.are_you_sure')}, method: :delete -%>
          <%- end -%>
        </td>
      </tr>
    <%- end -%>
    </table>

    <%= paginate(@classifications) -%>

  </div>

  <div class="col">
    <div class="card card-body">
      <ul>
        <%- if policy(Classification).create? -%>
          <%- if @classification_type -%>
            <li><%= link_to t('page.new', model: t('activerecord.models.classification')), new_classification_type_classification_path(@classification_type) -%></li>
          <%- else -%>
            <li><%= link_to t('page.new', model: t('activerecord.models.classification')), new_classification_path -%></li>
          <%- end -%>
        <%- end -%>
      </ul>
    </div>
  </div>
</div>

app/views/classifications/new.html.erb
<div class="row">
  <div class="col-md-9">
    <h1 class="title"><%=  t('page.new', model: t('activerecord.models.classification')) -%></h1>
    <%= render 'form' %>
  </div>

  <div class="col">
    <div class="card card-body">
      <ul>
        <li><%= link_to t('page.back'), :back -%></li>
      </ul>
    </div>
  </div>
</div>

app/views/classifications/show.html.erb
<div class="row">
  <div class="col-md-9">
    <h1 class="title"><%= t('page.showing', model: t('activerecord.models.classification')) -%></h1>
    <p id="notice"><%= notice %></p>

    <p>
      <strong><%= t('activerecord.models.classification_type') -%>:</strong>
      <%= link_to @classification.classification_type.display_name, @classification.classification_type %>
    </p>

    <p>
      <strong><%= t('activerecord.attributes.classification.category') -%>:</strong>
      <%= @classification.category %>
    </p>

    <p>
      <strong><%= t('activerecord.attributes.classification.label') -%>:</strong>
      <%= @classification.label %>
    </p>

    <p>
      <strong><%= t('activerecord.attributes.classification.url') -%>:</strong>
      <%= link_to @classification.url, URI.parse(@classification.url).to_s if @classification.url %>
    </p>

    <p>
      <strong><%= t('activerecord.attributes.classification.note') -%>:</strong>
      <%= @classification.note %>
    </p>

  </div>

  <div class="col">
    <div class="card card-body">
      <ul>
        <%- if policy(@classification).update? -%>

          <li><%= link_to t('page.edit'), edit_classification_path(@classification) %></li>
        <%- end -%>
        <li><%= link_to t('page.back'), :back -%></li>
      </ul>
    </div>
  </div>
</div>