config/routes.rb
Rails.application.routes.draw do
  resources :subject_heading_types
  resources :classification_types
  resources :classifications
  resources :subject_types
  resources :subjects
end

app/controllers/classification_types_controller.rb
class ClassificationTypesController < ApplicationController
  before_action :set_classification_type, only: [:show, :edit, :update, :destroy]
  before_action :check_policy, only: [:index, :new, :create]

  # GET /classification_types
  # GET /classification_types.json
  def index
    @classification_types = ClassificationType.order(:position)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @classification_types }
    end
  end

  # GET /classification_types/1
  # GET /classification_types/1.json
  def show
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @classification_type }
    end
  end

  # GET /classification_types/new
  # GET /classification_types/new.json
  def new
    @classification_type = ClassificationType.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @classification_type }
    end
  end

  # GET /classification_types/1/edit
  def edit
  end

  # POST /classification_types
  # POST /classification_types.json
  def create
    @classification_type = ClassificationType.new(classification_type_params)

    respond_to do |format|
      if @classification_type.save
        format.html { redirect_to @classification_type, notice:  t('controller.successfully_created', model: t('activerecord.models.classification_type')) }
        format.json { render json: @classification_type, status: :created, location: @classification_type }
      else
        format.html { render action: "new" }
        format.json { render json: @classification_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /classification_types/1
  # PUT /classification_types/1.json
  def update
    if params[:move]
      move_position(@classification_type, params[:move])
      return
    end

    respond_to do |format|
      if @classification_type.update(classification_type_params)
        format.html { redirect_to @classification_type, notice:  t('controller.successfully_updated', model: t('activerecord.models.classification_type')) }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @classification_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /classification_types/1
  # DELETE /classification_types/1.json
  def destroy
    @classification_type.destroy

    respond_to do |format|
      format.html { redirect_to classification_types_url, notice: t('controller.successfully_deleted', model: t('activerecord.models.classification_type')) }
      format.json { head :no_content }
    end
  end

  private
  def set_classification_type
    @classification_type = ClassificationType.find(params[:id])
    authorize @classification_type
  end

  def check_policy
    authorize ClassificationType
  end

  def classification_type_params
    params.require(:classification_type).permit(:name, :display_name, :note)
  end
end

app/views/classification_types/_form.html.erb
<%= form_for(@classification_type) do |f| %>
  <%= f.error_messages %>

  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, required: true, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :display_name %>
    <%= f.text_area :display_name, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :note %>
    <%= f.text_area :note, class: 'form-control' %>
  </div>
  <div class="actions">
    <%= f.submit class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/classification_types/edit.html.erb
<div class="row">
  <div class="col-md-9">
    <h1 class="title"><%= t('page.editing', model: t('activerecord.models.classification_type')) -%></h1>
    <%= render 'form' %>
  </div>

  <div class="col">
    <div class="card card-body">
      <ul>
        <li><%= link_to t('page.show'), @classification_type -%></li>
        <li><%= link_to t('page.back'), classification_types_path -%></li>
      </ul>
    </div>
  </div>
</div>

app/views/classification_types/index.html.erb
<div class="row">
  <div class="col-md-9">
    <h1 class="title"><%= t('page.listing', model: t('activerecord.models.classification_type')) -%></h1>
    <p id="notice"><%= notice %></p>

    <table class="table table-striped index">
      <tr>
        <th id="position"></th>
        <th><%= t('activerecord.attributes.classification_type.name') -%></th>
        <th>
          <%= t('activerecord.attributes.classification_type.display_name') -%>
          /
          <%= t('activerecord.attributes.classification_type.note') -%>
        </th>
        <th></th>
      </tr>

    <%- @classification_types.each do |classification_type| -%>
      <tr class="line<%= cycle("0", "1") -%>">
        <td>
          <%- if policy(classification_type).update? -%>
            <%= move_position(classification_type) -%>
          <%- end -%>
        </td>
        <td><%= classification_type.name -%></td>
        <td>
          <%= link_to classification_type.display_name, classification_type -%>
          <br />
          <%= classification_type.note %>
        </td>
        <td>
          <%- if policy(classification_type).update? -%>
            <%= link_to t('page.edit'), edit_classification_type_path(classification_type) -%>
          <% end %>
          <%- if policy(classification_type).destroy? -%>
            <%= link_to t('page.destroy'), classification_type_path(classification_type), data: {confirm: t('page.are_you_sure')}, method: :delete -%>
          <%- end -%>
        </td>
      </tr>
    <%- end -%>
    </table>

  </div>

  <div class="col">
    <div class="card card-body">
      <ul>
        <%- if policy(ClassificationType).create? -%>
          <li><%= link_to t('page.new', model: t('activerecord.models.classification_type')), new_classification_type_path -%></li>
        <%- end -%>
      </ul>
    </div>
  </div>
</div>

app/views/classification_types/new.html.erb
<div class="row">
  <div class="col-md-9">
    <h1 class="title"><%= t('page.new', model: t('activerecord.models.classification_type')) -%></h1>
    <%= render 'form' %>
  </div>

  <div class="col">
    <div class="card card-body">
      <ul>
        <li><%= link_to t('page.back'), classification_types_path -%></li>
      </ul>
    </div>
  </div>
</div>

app/views/classification_types/show.html.erb
<div class="row">
  <div class="col-md-9">
    <h1 class="title"><%= t('page.showing', model: t('activerecord.models.classification_type')) -%></h1>
    <p id="notice"><%= notice %></p>

    <p>
      <strong><%= t('activerecord.attributes.classification_type.name') -%>:</strong>
      <%= @classification_type.name -%>
    </p>

    <p>
      <strong><%= t('activerecord.attributes.classification_type.display_name') -%>:</strong>
      <%= @classification_type.display_name -%>
    </p>

    <p>
      <strong><%= t('activerecord.attributes.classification_type.note') -%>:</strong>
      <%= @classification_type.note -%>
    </p>

  </div>

  <div class="col">
    <div class="card card-body">
      <ul>
        <%- if policy(@classification_type).update? -%>
          <li><%= link_to t('page.edit'), edit_classification_type_path(@classification_type) -%></li>
        <%- end -%>
        <li><%= link_to t('page.back'), :back -%></li>
      </ul>
    </div>
  </div>
</div>